name: Build Project

on:
 push:
   branches:
     - test-branch

  repository_dispatch:

jobs:
  build:
    runs-on: macOS-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v1
        with:
            ref: test-branch
      
      - name: Install gpg
        run: brew install gnupg
        
      - name: Switch XCode Version
        run: sudo xcode-select -s /Applications/Xcode_11.2.1.app
        
      - name: Set Permissions for decrypt_secrets.sh file
        run: chmod +x .github/secrets/decrypt_secrets.sh
        
      - name: Setup provisioning profile
        run: ./.github/secrets/decrypt_secrets.sh
        env:
          IOS_PROFILE_KEY: ${{ secrets.IOS_PROFILE_KEY }}

      - name: Cache Pods dependencies
        uses: actions/cache@v1
        with:
          path: ./Pods   #ios/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Install pod dependencies
        run: |
          pod install
          
      # - name: Setup Firebase CLI
      #   run: npm install -g firebase-tools

      # - name: Install Fastlane Plugin App Distribution
      #   run: fastlane add_plugin firebase_app_distribution

      # - name: Install Fastlane Plugin Versioning
      #   run: fastlane add_plugin versioning

      # # - name: Unset CFProcessPath & run fastlane
      # #   run: unset CFProcessPath; bundle exec fastlane vertical_app_build --env AlumniID-Dev
          
      # - name: Fastlane Action
      #   uses: maierj/fastlane-action@v1.4.0
      #   with:
      #       lane: 'vertical_app_build --env AlumniID-Dev'

      # - name: Show contents of Ezport Options
      #   run: cat ./exportOptions.plist


