name: Build Project

on:
  gollum:
   branches:
    - master

  push:
   branches:
     - test-branch

  repository_dispatch:

jobs:
  build:
    runs-on: macOS-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v1
        with:
            ref: test-branch
        
      - name: Switch XCode Version
        run: sudo xcode-select -s /Applications/Xcode_11.4.1.app

      - name: Access payload
        env: BUILD_TARGET: ${{ github.event.pages[0].page_name }}
        run: echo $BUILD_TARGET
        
      # - name: Cache Pods dependencies
      #   uses: actions/cache@v1
      #   id: pods-cache
      #   with:
      #     path: Pods   #ios/Pods
      #     key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
      #     # key: ${{ runner.os }}-pods-${{ hashFiles('/Podfile.lock') }}
      #     restore-keys: |
      #       ${{ runner.os }}-pods-

      # - name: Pod install 
      #   if: steps.pods-cache.outputs.cache-hit != 'true'
      #   run: |
      #       pod install

      # - name: Replace the old podfile.lock
      #   if: steps.pods-cache.outputs.cache-hit == 'true'
      #   run: |
      #       cp ./Pods/Manifest.lock ./Podfile.lock
            

      # - name: List Pods 
      #   run: |
      #     ls ./Pods
      #     ls .

      # - name: Setup Firebase CLI
      #   run: npm install -g firebase-tools

      # - name: Install Fastlane Plugin App Distribution
      #   run: fastlane add_plugin firebase_app_distribution

      # - name: Install Fastlane Plugin Versioning
      #   run: fastlane add_plugin versioning
        
      # - name: Set Permissions for decrypt_secrets.sh file
      #   run: chmod +x .github/secrets/decrypt_secrets.sh
          
      # - name: Setup provisioning profile
      #   run: ./.github/secrets/decrypt_secrets.sh
      #   env:
      #       TEST_REPO_SECRET: ${{ secrets.TEST_REPO_SECRET }}
        
      # - name: Fastlane Action
      #   uses: maierj/fastlane-action@v1.4.0
      #   with:
      #       lane: 'vertical_app_build --env AlumniID-Dev'



